/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Solarliu (https://sketchfab.com/jacky15621419)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/park-facility-asset-1b99e093f1194aea921d4de4ca654800
title: Park facility asset
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ParkScene(props) {
  const { nodes, materials } = useGLTF('/models/park-facility/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-546.74, 517.28, -1143.37]} rotation={[0, -1.1, -0.51]} />
          <group position={[514.52, -1.23, 6.87]} rotation={[Math.PI, 0, -Math.PI]} scale={4}>
            <mesh geometry={nodes.slider_2_brown_0.geometry} material={materials.brown} />
            <mesh geometry={nodes.slider_2_gray_0.geometry} material={materials.gray} />
            <mesh geometry={nodes.slider_2_concrete_0.geometry} material={materials.concrete} />
            <mesh geometry={nodes.slider_2__0.geometry} material={materials.slider_2__0} />
            <mesh geometry={nodes.slider_2_concrete1_0.geometry} material={materials['concrete.1']} />
          </group>
          <group position={[0, 0, 159.71]} scale={0.2}>
            <mesh geometry={nodes.rest_2_concrete_1.geometry} material={materials.concrete} />
            <mesh geometry={nodes.rest_2_roof_0.geometry} material={materials.roof} />
          </group>
          <group position={[-313.4, 0, -433.53]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.2}>
            <mesh geometry={nodes.swing_D_Y_0.geometry} material={materials.material} />
            <mesh geometry={nodes.swing_D_B_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.swing_D_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.swing_D_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.swing_D_R_0.geometry} material={materials.material_10} />
          </group>
          <group position={[-413.4, 0, -433.53]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.2}>
            <mesh geometry={nodes.swing_S_R_0.geometry} material={materials.material_10} />
            <mesh geometry={nodes.swing_S_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.swing_S_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.swing_S_B_0.geometry} material={materials.material_7} />
          </group>
          <group position={[-513.4, 0, -433.53]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={2.2}>
            <mesh geometry={nodes.swing_H_B_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.swing_H_R_0.geometry} material={materials.material_10} />
            <mesh geometry={nodes.swing_H_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.swing_H_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.swing_H_Y_0.geometry} material={materials.material} />
          </group>
          <group position={[290.2, 0, -512.12]} scale={2}>
            <mesh geometry={nodes.Lamp__0.geometry} material={materials.slider_2__0} />
            <mesh geometry={nodes.Lamp_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Lamp_light_0.geometry} material={materials.light} />
          </group>
          <group position={[-21.19, 0, -291.57]} rotation={[0, Math.PI / 2, 0]} scale={2.5}>
            <mesh geometry={nodes.Slider02_B_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.Slider02_Y_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Slider02_R_0.geometry} material={materials.material_10} />
            <mesh geometry={nodes.Slider02_concrete_0.geometry} material={materials.concrete} />
            <mesh geometry={nodes.Slider02_gray_0.geometry} material={materials.gray} />
          </group>
          <group position={[-476.99, 0, -89.79]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={3}>
            <mesh geometry={nodes.Dount_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Dount_B_0.geometry} material={materials.material_7} />
            <mesh geometry={nodes.Dount_gray_0.geometry} material={materials.gray} />
            <mesh geometry={nodes.Dount_concrete_0.geometry} material={materials.concrete} />
          </group>
          <mesh geometry={nodes.Plane_grass_0.geometry} material={materials.grass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/park-facility/scene.gltf')
