/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: iysif (https://sketchfab.com/iysif)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pubg-white-suit-32779d2f35e449d092dae53f88ab7753
title: Pubg White Suit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PubG(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, -798.54, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={5.86}
          >
            <mesh
              geometry={nodes.Mesh_0017rip_mat0007_0.geometry}
              material={materials["mat0.007"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={6.71}>
            <mesh
              geometry={nodes.Mesh_0051rip_mat0019_0.geometry}
              material={materials["mat0.019"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={6.71}>
            <mesh
              geometry={nodes.Mesh_0240rip_mat0022_0.geometry}
              material={materials["mat0.022"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={6.71}>
            <mesh
              geometry={nodes.Mesh_0269rip_mat0023_0.geometry}
              material={materials["mat0.023"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={6.71}>
            <mesh
              geometry={nodes.Mesh_0049rip_mat0024_0.geometry}
              material={materials["mat0.024"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={6.71}>
            <mesh
              geometry={nodes.Mesh_0171rip_mat0025_0.geometry}
              material={materials["mat0.025"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
